services:
  database:
    image: "postgres"
    restart: "always"
    container_name: "cyf-postgres"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-cyf}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-opensesame}"
    ports:
      - "5432:5432"
    volumes:
     - "./build-rhythms.sql:/docker-entrypoint-initdb.d/build-rhythms.sql"
